name: dukkantek_test
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2


  # A Dart package that helps to implement value
  # based equality without needing to explicitly override == and hashCode.
  equatable: ^2.0.2

  # A composable, Future-based library for making HTTP requests.
  http: ^0.13.1

  # A powerful Http client for Dart
  dio: ^4.0.4

  # Pretty Dio logger is a Dio interceptor that logs network calls in a pretty, easy to read format.
  pretty_dio_logger: ^1.1.1



  #  ============= State Management ==================

  # MobX is a library for reactively managing the state of your applications. Use the power of
  # observables, actions, and reactions to supercharge your Dart and Flutter apps.
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.3+2


  # flutter_bloc is a library for state managing the state of your applications.
  flutter_bloc: ^8.0.1

  # Custom event transformers inspired by ember concurrency.
  # Built to be used with the bloc state management package.
  bloc_concurrency: ^0.2.0

  # An helper to easily exposes a value using InheritedWidget without having to write one.
  provider: ^6.0.2



  #  ============= Useful Utils ==================

  # Toast Library for Flutter, Easily create toast messages in single line of code
  fluttertoast: ^8.0.8

  # This package provides internationalization and localization facilities, including message
  # translation, plurals and genders, date/number formatting and parsing, and bidirectional text.
  intl: ^0.17.0

  # XXTEA is a fast and secure encryption algorithm. This is a XXTEA library for Dart.
  xxtea: ^2.1.0

  path_provider: ^2.0.1

  # for dependency injection
  injectable: ^1.4.1
  get_it:

  #A Flutter package that can be used to extract the locales that are currently defined on a device with the current locale set as the first in the list.
  devicelocale: ^0.5.0

  # Flutter plugin for discovering the state of the network (WiFi & mobile/cellular) connectivity on Android and iOS.
  connectivity_plus: ^2.2.0

  connectivity: ^3.0.6

  #  intl_utils: ^2.6.0
  # A Flutter package with custom implementation of the Side Menu (Drawer)
  flutter_zoom_drawer: ^2.1.2


  #  A Flutter plugin that provides a WebView widget on Android and iOS.
  webview_flutter: ^2.0.4



  #  ============= UI Helper ==================
  # A package provides an easy way to add shimmer effect in Flutter project
  shimmer: ^2.0.0


  # A collection of loading indicators animated with flutter.
  flutter_spinkit: ^5.1.0

  # An SVG rendering and widget library for Flutter,
  # which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^0.22.0


  #Flutter library to load and cache network images.
  #Can also be used with placeholder and error widgets.
  cached_network_image: ^3.2.0

  #Flutter Page Transition Package which is the transition second page
  page_transition: ^2.0.4


  # This package helps you daily usable function and ready made Widgets with ease.
  nb_utils: ^4.4.10


  # A modal progress indicator widget
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1


  #  ============= Local Data Storage ==================

  # Lightweight and blazing fast key-value database written in pure Dart.
  # Strongly encrypted using AES-256.
  hive: ^2.0.5

  # Extension for Hive. Makes it easier to use Hive in Flutter apps.
  hive_flutter: ^1.1.0


  # An helper to easily exposes a value using InheritedWidget without having to write one.
  sembast: ^3.0.2

  # The following adds the shared pref as a dependency in your application
  shared_preferences: ^2.0.11



  #  ============= GOOGLE Packages ==================

  #  google_sign_in: ^5.2.1
  #  firebase_crashlytics: ^2.4.4
  #  firebase_performance: ^0.8.0+3
  #  firebase_core: ^1.10.6

#  # The google_fonts package for Flutter allows you to easily use any of the 977 fonts
#  # (and their variants) from fonts.google.com in your Flutter app.
#  google_fonts: ^2.2.0

  #  ============= Animations Packages ==================

  # Easily add staggered animations to your ListView, GridView,
  # Column and Row children as shown in Material Design guidelines
  flutter_staggered_animations: ^1.0.0

  # Beautiful animations inspired on Animate.css,
  # every animation is a widget that contains default but customizable values that look attractive.
  animate_do: ^2.0.0

  #A flutter package project which contains a collection of cool and beautiful text animations.
  animated_text_kit: ^4.2.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

  # The following adds the launcher icon support to your application.
  # run below mentioned commands to generate launcher icons
  # flutter packages get
  # flutter packages pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.9.2

  injectable_generator: ^1.5.2
  json_serializable: ^6.1.3
  mobx_codegen: ^2.0.3+1
  build_runner: ^2.1.7
  mockito: ^5.0.17
  hive_generator: ^1.1.1
  analyzer: ^2.8.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/